import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fb' },
  dashboardButton: {
    backgroundColor: '#1e293b',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  dashboardButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
  exportButton: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#2f6ea8',
  },
  exportButtonDisabled: {
    opacity: 0.6,
  },
  exportButtonText: {
    color: '#2f6ea8',
    fontWeight: 'bold',
    fontSize: 14,
  },
  reportButton: {
    backgroundColor: '#eef6ff',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  reportButtonText: {
    color: '#1d4ed8',
    fontWeight: 'bold',
    fontSize: 14,
  },
  usersButton: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#86efac',
  },
  usersButtonText: {
    color: '#15803d',
    fontWeight: 'bold',
    fontSize: 14,
  },
  importButton: {
    backgroundColor: '#fff7ed',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#fdba74',
  },
  importButtonText: {
    color: '#c2410c',
    fontWeight: 'bold',
    fontSize: 14,
  },
  searchFilterContainer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 4,
  },
  searchInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 40,
    fontSize: 14,
    color: '#334155',
  },
  filterScrollView: { marginTop: 8, marginBottom: 4 },
  filterContentContainer: { gap: 8, paddingRight: 16 },
  filterPill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  filterPillActive: { backgroundColor: '#2f6ea8', borderColor: '#2f6ea8' },
  filterPillText: { fontSize: 12, fontWeight: '600', color: '#64748b' },
  filterPillTextActive: { color: '#fff' },
  sectorLabel: { marginTop: 3, marginBottom: 7, color: '#475569', fontSize: 12, fontWeight: '800' },
  advancedFiltersRow: { flexDirection: 'row', gap: 8 },
  advancedFilter: { flex: 1 },
  sectorSelect: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: '#bfdbfe', backgroundColor: '#fff' },
  sectorSelectContent: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectorSelectText: { flex: 1, color: '#1e3a8a', fontSize: 13, fontWeight: '800' },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: { marginTop: 10, color: '#64748b', fontSize: 14 },
  emptyText: { color: '#64748b', fontSize: 15, textAlign: 'center' },
  listContainer: { padding: 16, paddingBottom: 90 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  patrimonioText: { fontSize: 16, fontWeight: 'bold', color: '#2f6ea8' },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badgeText: { fontSize: 12, fontWeight: '700' },
  tipoText: {
    fontSize: 15,
    color: '#334155',
    fontWeight: '500',
    marginBottom: 6,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  setorText: { fontSize: 13, color: '#64748b' },
  responsavelCardText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1e3a8a',
    maxWidth: '60%',
  },
  responsavelVazioText: { color: '#94a3b8', fontWeight: '400' },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2f6ea8',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  fabText: { color: '#fff', fontSize: 28, fontWeight: '300', marginBottom: 2 },
  overlayContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 50,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  scanInstructions: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  scanTarget: {
    width: 320,
    height: 140,
    borderWidth: 2,
    borderColor: '#2f6ea8',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  scanLaser: {
    width: '90%',
    height: 2,
    backgroundColor: '#ef4444',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  closeScanButton: {
    backgroundColor: '#ef4444',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  closeScanText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});
